#!/usr/bin/env node
/*
 * Build step. Reads blocklist.json (the single source of truth) and regenerates:
 *   - manifest.json  -> scoped host_permissions + content-script matches
 *   - src/blocklist.data.js -> DEFAULT_BLOCKLIST baked in for the runtime
 *
 * Blocking rules are created dynamically at runtime (per-site actions), so there
 * is no static ruleset to generate.
 *
 * Run after editing blocklist.json:  node tools/build.js
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");

function read(p) {
  return JSON.parse(fs.readFileSync(path.join(root, p), "utf8"));
}
function write(p, text) {
  fs.writeFileSync(path.join(root, p), text);
}

const blocklist = read("blocklist.json");
const domains = [
  ...new Set(
    (blocklist.domains || [])
      .map((d) => String(d).trim().toLowerCase())
      .filter(Boolean)
  )
];

// `*://*.vg.no/*` matches the apex domain AND every subdomain.
const patterns = domains.map((d) => `*://*.${d}/*`);

// 1) Runtime copy of the defaults, loaded everywhere as a classic script.
write(
  "src/blocklist.data.js",
  "/* AUTO-GENERATED by tools/build.js from blocklist.json. Do not edit by hand. */\n" +
    "const DEFAULT_BLOCKLIST = " +
    JSON.stringify(domains, null, 2) +
    ";\n"
);

// 2) Scoped permissions + content-script matches in the manifest.
const manifest = read("manifest.json");
manifest.host_permissions = patterns;
manifest.content_scripts[0].matches = patterns;
write("manifest.json", JSON.stringify(manifest, null, 2) + "\n");

console.log(
  "Built " +
    domains.length +
    " domains -> manifest.json, src/blocklist.data.js"
);
