#!/usr/bin/env node
/*
 * Build step. Reads blocklist.json (the single source of truth) and regenerates:
 *   - manifest.json  -> scoped host_permissions + content-script matches
 *   - rules/schibsted.json -> static declarativeNetRequest ruleset (stop-page mode)
 *   - src/blocklist.data.js -> DEFAULT_BLOCKLIST baked in for the runtime
 *
 * Run after editing blocklist.json:  node tools/build.js
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");

function read(p) {
  return JSON.parse(fs.readFileSync(path.join(root, p), "utf8"));
}
function write(p, text) {
  fs.writeFileSync(path.join(root, p), text);
}

const blocklist = read("blocklist.json");
const domains = [
  ...new Set(
    (blocklist.domains || [])
      .map((d) => String(d).trim().toLowerCase())
      .filter(Boolean)
  )
];

// `*://*.vg.no/*` matches the apex domain AND every subdomain.
const patterns = domains.map((d) => `*://*.${d}/*`);

// 1) Runtime copy of the defaults, loaded everywhere as a classic script.
write(
  "src/blocklist.data.js",
  "/* AUTO-GENERATED by tools/build.js from blocklist.json. Do not edit by hand. */\n" +
    "const DEFAULT_BLOCKLIST = " +
    JSON.stringify(domains, null, 2) +
    ";\n"
);

// 2) Static ruleset: each default domain redirects to the bundled stop page.
//    The domain is baked into the path so the page can name what it blocked.
const rules = domains.map((d, i) => ({
  id: i + 1,
  priority: 1,
  action: {
    type: "redirect",
    redirect: {
      extensionPath: "/src/blocked.html?domain=" + encodeURIComponent(d)
    }
  },
  condition: { requestDomains: [d], resourceTypes: ["main_frame"] }
}));
fs.mkdirSync(path.join(root, "rules"), { recursive: true });
write("rules/schibsted.json", JSON.stringify(rules, null, 2) + "\n");

// 3) Scoped permissions + content-script matches in the manifest.
const manifest = read("manifest.json");
manifest.host_permissions = patterns;
manifest.content_scripts[0].matches = patterns;
write("manifest.json", JSON.stringify(manifest, null, 2) + "\n");

console.log(
  "Built " +
    domains.length +
    " domains -> manifest.json, rules/schibsted.json, src/blocklist.data.js"
);
